[project]
name = "vercel-blob-api"
version = "0.1.0"
description = "This is a simple FastAPI application to upload files to Vercel Blob storage."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.117.1",
]
